# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2luHnaxxE4VaAAgRNUtqLYe4RgWzVs4
"""

import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/amazon.csv.zip')  # Replace with your file path

df.head()

# Total sales by product
# There is no 'Sales' column in the dataframe, grouping by product name instead.
product_counts = df.groupby('product_name').size().reset_index(name='count')
print(product_counts)

# Sales by product and region
# There is no 'Sales' or 'Region' column in the dataframe. Grouping by product name instead.
product_counts = df.groupby('product_name').size().reset_index(name='count')
print(product_counts)

# Sales by product and region
# There is no 'Sales' or 'Region' column in the dataframe. Grouping by product name instead.
product_counts = df.groupby('product_name').size().reset_index(name='count')
print(product_counts)

import matplotlib.pyplot as plt

# Plot total sales by product
product_counts.plot(kind='bar', title='Total Sales by Product', figsize=(10, 6))
plt.xlabel('Product')
plt.ylabel('Sales')
plt.tight_layout()
plt.show()